version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: kochhealth-vitals-db
    environment:
      POSTGRES_DB: healthAppVitalsDb
      POSTGRES_USER: maitreyakocharekar
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
