version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: kochhealth-user-db
    environment:
      POSTGRES_DB: healthAppUserDb
      POSTGRES_USER: maitreyakocharekar
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
